version: '3.8'

services:
  notify:
    image: notify
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - default

  mongo:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    networks:
      - default

volumes:
  mongo:
