version: '3.8'

services:
  template:
    image: template
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    restart: unless-stopped
